### ISSUE TITLE
跑着跑着项目就会panic

### ISSUE THREAD

**Issue by yangyuw** [du2016/web-terminal-in-go#5]
重现方法是在已经成功连接的基础上按ctrl+shift+R刷新页面, 有时候页面打开久了也会panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa6b171]

goroutine 27 [running]:
github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/github.com/docker/docker/pkg/term.RestoreTerminal(0x0, 0x0, 0x0, 0x0)
	D:/code/go/src/github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/github.com/docker/docker/pkg/term/term_windows.go:130 +0x31
github.com/du2016/web-terminal-in-go/k8s-webshell/controllers.Handler.func2()
	D:/code/go/src/github.com/du2016/web-terminal-in-go/k8s-webshell/controllers/terminalws.go:128 +0x49
github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Close.func1()
	D:/code/go/src/github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go:65 +0x8e
sync.(*Once).Do(0xc00001f760, 0xc000489d00)
	D:/Go/src/sync/once.go:44 +0xe7
github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Close(0xc00001f740)
	D:/code/go/src/github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go:63 +0x73
github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/k8s.io/kubernetes/pkg/util/interrupt.(*Handler).Run(0xc00001f740, 0xc00001f710, 0x0, 0x0)
	D:/code/go/src/github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/k8s.io/kubernetes/pkg/util/interrupt/interrupt.go:103 +0x128
github.com/du2016/web-terminal-in-go/k8s-webshell/controllers.Handler(0xc00006e240, 0x16a3aa8, 0x7, 0x0, 0x0)
	D:/code/go/src/github.com/du2016/web-terminal-in-go/k8s-webshell/controllers/terminalws.go:129 +0x687
github.com/du2016/web-terminal-in-go/k8s-webshell/controllers.TerminalSockjs.ServeHTTP.func1(0x18ad580, 0xc0003305a0)
	D:/code/go/src/github.com/du2016/web-terminal-in-go/k8s-webshell/controllers/terminalws.go:141 +0x203
created by github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/gopkg.in/igm/sockjs-go.v2/sockjs.(*handler).sockjsWebsocket
	D:/code/go/src/github.com/du2016/web-terminal-in-go/k8s-webshell/vendor/gopkg.in/igm/sockjs-go.v2/sockjs/websocket.go:31 +0x2c0

Debugger finished with exit code 0
```

**Comment by du2016** [comment]
@yu-yang2 你有对代码做修改么，我直接运行起来没有遇到panic的问题，另外基于windows运行我没测试过，代码里有涉及系统调用。

**Comment by yangyuw** [comment]
@du2016 确实是在Windows下面调试的时候 docker 的 term_windows.go 文件报的错，等我部署到Linux测试下。
